apiVersion: apps/v1
kind: Deployment
metadata:
  name: necapp
  namespace: sdev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: necapp
  template:
    metadata:
      labels:
        app: necapp
    spec:
      containers:
        - name: necapp
          image: necapp:latest
          imagePullPolicy: Never  # Use local image, don’t pull from a registry
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: necapp-service
  namespace: sdev
spec:
  selector:
    app: necapp
  ports:
    - port: 3000
      targetPort: 3000
  type: ClusterIP  # Use NodePort or LoadBalancer if you need external access