openapi: '3.0.3'
info:
  title: NoErrorCode REST API
  version: '1.0'
servers:
  - url: https://localhost:12121/rest/v1
paths:
  /auth:
    post:
      summary: "Authenticate username and password"
      operationId: AuthUser
      requestBody:
        content:
          application/json:
            schema: 
              $ref: '#/components/schemas/Auth'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponse'
        '403':
          description: Forbidden
  /stats:
    get:
      summary: "Get stats configuration"
      operationId: GetStats
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StatsResponse'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
    post:
      summary: "Update stat"
      operationId: UpdateStat
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StatUpdate'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StatUpdateResponse'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
  /characters:
    get:
      summary: "Retrieve character IDs"
      operationId: GetCharacters
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#components/schemas/CharactersRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CharactersResponse'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
components:
  schemas:
    Auth:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
    AuthResponse:
      type: object
      properties:
        code:
          type: integer
          format: uint32
        error:
          type: string
        token:
          type: string
    StatsResponse:
      type: object
      properties:
        code:
          type: integer
          format: uint32
        error:
          type: string
        stats:
          type: array
          items:
            $ref: '#components/schemas/Stat'
    StatUpdateResponse:
      type: object
      properties:
        code:
          type: integer
          format: uint32
        error:
          type: string
    CharactersRequest:
      type: object
      properties:
        user_id:
          type: integer
          format: uint32
    CharactersResponse:
      type: object
      properties:
        ids:
          type: array
          items:
            $ref: '#components/schemas/Ids'
    Ids:
      type: integer
    Stat:
      type: object
      properties:
        id:
          type: integer
          format: uint32
        name:
          type: string
        description:
          type: string
        value_type:
          type: string
        is_required:
          type: boolean
        is_unique:
          type: boolean
        unique_scope:
          type: integer
          format: uint32
        update_permission:
          type: integer
          format: uint32
        string:
          type: object
          properties:
            default:
              type: string
            min:
              type: integer
              format: int32
            max:
              type: integer
              format: int32
        integer:
          type: object
          properties:
            default:
              type: string
            min:
              type: integer
              format: int32
            max:
              type: integer
              format: int32
        float:
          type: object
          properties:
            default:
              type: string
            min:
              type: number 
              format: float 
            max:
              type: number 
              format: float
    StatUpdate:
      type: object
      properties:
        id:
          type: integer
          format: uint32
        description:
          type: string
        is_required:
          type: boolean
        is_unique:
          type: boolean
        unique_scope:
          type: integer
          format: uint32
        update_permission:
          type: integer
          format: uint32
        string:
          type: object
          properties:
            default:
              type: string
            min:
              type: integer
              format: int32
            max:
              type: integer
              format: int32
        integer:
          type: object
          properties:
            default:
              type: string
            min:
              type: integer
              format: int32
            max:
              type: integer
              format: int32
        float:
          type: object
          properties:
            default:
              type: string
            min:
              type: number 
              format: float 
            max:
              type: number 
              format: float